### PR TITLE
Create test suite

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
The current tests intentionally expose errors due to https://github.com/jackmaney/python-stdlib-list/issues/7 .  IMO the usefulness of this package is quite limited unless it is complete.

**Comment by jayvdb** [comment]
I'm happy to expand https://github.com/jackmaney/python-stdlib-list/pull/28/commits/ffc46e277a0705f475cd7f14b9b5c5040b939353 into multiple commits with more descriptive commit messages, but I'm going to focus on getting more tests written to expose the other missing module sets in a reliable manner.

I've avoided updating py26, py32 & py33 except the blindly obvious, as they should be either discarded or CI added to run the tests on them, if they are going to be supported.

Bad data is often worse than no data.

**Comment by ocefpaf** [comment]
@jayvdb thanks for this PR! It would be nice if we had an automated way to capture these missing modules.

**Comment by jayvdb** [comment]
The next set of tests almost provide that, at least for large subsets of the lists.

**Comment by ocefpaf** [comment]
@jayvdb this looks good to me. Do you mind running `isort` and `black` before we merge this?

**Comment by jayvdb** [comment]
ok

**Comment by jayvdb** [comment]
The set of modules still not validated is the DSOs.

**Comment by jayvdb** [comment]
@ocefpaf, I think this is about where this PR should end.  As you reviewed it half way, I havent done your style requests yet, so you can easily see the latter additions.
There are a few other stylistic/structural improvements I'd like to make before it is merged, like adding a `tests.__main__` to run all test classes together, and removing the top level `if` around classes in `test_platform`.  Also happy to re-organise anything else you see that needs doing.  I'll tidy it all up tmr.

**Comment by jayvdb** [comment]
@ocefpaf, probably best to get a review now, fix any critical issues, and get it merged asap, and iterate further after that when the repo is green.

**Comment by jayvdb** [comment]
Hello?

**Pull request merged**
