### PR TITLE
add auto-publish

### PR DESCRIPTION
**Pull request by ocefpaf**
There are no code tests but this bare bones Travis-CI will test the source tarball and auto-upload it to PyPI when we tag a new version on GitHub.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jackmaney I'm sorry to bug you again but I believe you would have to enable Travis-CI for this repository. If that is a problem I can change the configuration to upload from my fork instead.

**Comment by ocefpaf** [comment]
With the last commit Python 3.7 will fail as expected. It should pass after #15 is merged.

**Comment by jackmaney** [comment]
@ocefpaf I believe I've correctly set up Travis CI with this repo (although I don't have much experience with it, so I'm not completely certain).

**Comment by ocefpaf** [comment]
> @ocefpaf I believe I've correctly set up Travis CI with this repo (although I don't have much experience with it, so I'm not completely certain).

Looks like it is working! Thanks a lot and sorry to bug you again.

**Comment by jackmaney** [comment]
No worries.

**Pull request merged**
